name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

  

flutter:
  uses-material-design: true
  assets:
   - assets/s.jpg
  